name: klasifikasi_penyakit_padi
description: "Deteksi penyakit padi menggunakan deep learning berbasis Flutter"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_modular: ^5.0.3
  http: ^1.1.0
  image_picker: ^1.0.4
  http_parser: ^4.0.2
  connectivity_plus: ^5.0.0
  shared_preferences: ^2.2.1
  device_info_plus: ^9.0.3
  uuid: ^4.0.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/1.png"

flutter:
  uses-material-design: true
